USE [master]
GO

/****** Object:  Database [cinema]    Script Date: 28.03.2026 17:50:13 ******/
CREATE DATABASE [cinema]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cinema', FILENAME = N'C:\Users\Admin\cinema.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cinema_log', FILENAME = N'C:\Users\Admin\cinema_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cinema].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cinema] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cinema] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cinema] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cinema] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cinema] SET ARITHABORT OFF 
GO

ALTER DATABASE [cinema] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cinema] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cinema] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cinema] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cinema] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cinema] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cinema] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cinema] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cinema] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cinema] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cinema] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cinema] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cinema] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cinema] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cinema] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cinema] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cinema] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cinema] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [cinema] SET  MULTI_USER 
GO

ALTER DATABASE [cinema] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cinema] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cinema] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cinema] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [cinema] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cinema] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [cinema] SET QUERY_STORE = OFF
GO

ALTER DATABASE [cinema] SET  READ_WRITE 
GO

