//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinoshechka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public int UserID { get; set; }
        public int SessionID { get; set; }
        public int SeatID { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
